backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
 - label: "Content"
   name: "content"
   files:
    - label: "Home Page"
      name: "home"
      file: "_data/home.yml"
      fields:
        - {label: "Title", name: title, widget: string}
    - label: "Gallery"
      name: "gallery"
      file: "_data/gallery.yml"
      fields:
        - label: "Area"
          name: "area"
          widget: list
          fields:
            - {label: "Title", name: title, widget: string}
            - {label: "Image", name: image, widget: image}
        - label: "Studio Perupa"
          name: "studio"
          widget: list
          fields:
            - {label: "Title", name: title, widget: string}
            - {label: "Image", name: image, widget: image}
        - label: "Kelas Gambar"
          name: "kelas"
          widget: list
          fields:
            - {label: "Title", name: title, widget: string}
            - {label: "Image", name: image, widget: image}
    - label: "Event"
      name: "event"
      file: "_data/event.yml"
      fields:
          - label: "Event List"
            name: events
            widget: list
            fields:
              - {label: "Title", name: title, widget: string}
              - {label: "Image", name: image, widget: image}
              - {label: "Periode", name: periode, widget: string}
              - {label: "Location", name: location, widget: string}
              - {label: "Description", name: description, widget: markdown}
    - label: "Profile"
      name: "profile"
      file: "_data/profile.yml"
      fields:
          - {label: "Quote", name: quote, widget: markdown}
          - {label: "Description", name: description, widget: markdown}
          - {label: "Visi", name: visi, widget: markdown}
          - {label: "Misi", name: misi, widget: markdown}
          - label: "Founder List"
            name: founders
            widget: list
            fields:
              - {label: "Name", name: name, widget: string}
              - {label: "Image", name: image, widget: image}
              - {label: "Role", name: role, widget: string}
              - {label: "Description", name: description, widget: markdown}
    - label: "Profile"
      name: "profile"
      file: "_data/profile.yml"
      fields:
          - {label: "Home Description", name: description, widget: markdown}
          - label: "Program"
            name: program
            fields:
              - label: Edukasi
                name: edukasi
                field:
                  - {label: "Description", name: description, widget: markdown}
                  - {label: "Short Description", name: shortDesc, widget: markdown}
              - label: Kreasi
                name: edukasi
                field:
                  - {label: "Description", name: description, widget: markdown}
                  - {label: "Short Description", name: shortDesc, widget: markdown}
