backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
 - label: "Content"
   name: "content"
   files:
    - label: "Home Page"
      name: "home"
      file: "_data/home.yml"
      fields:
        - {label: "Title", name: title, widget: string}
    - label: "Gallery"
      name: "gallery"
      file: "_data/gallery.yml"
      fields:
        - label: "Area"
          name: "area"
          widget: list
          fields:
            - {label: "Title", name: title, widget: string}
            - {label: "Image", name: image, widget: image}
        - label: "Studio Perupa"
          name: "studio"
          widget: list
          fields:
            - {label: "Title", name: title, widget: string}
            - {label: "Image", name: image, widget: image}
        - label: "Kelas Gambar"
          name: "kelas"
          widget: list
          fields:
            - {label: "Title", name: title, widget: string}
            - {label: "Image", name: image, widget: image}
    - label: "Event"
      name: "event"
      file: "_data/event.yml"
      fields:
          - label: "Event List"
            name: events
            widget: list
            fields:
              - {label: "Title", name: title, widget: string}
              - {label: "Periode", name: periode, widget: string}
              - {label: "Location", name: location, widget: string}
              - {label: "Description", name: description, widget: markdown}
